### ISSUE TITLE
Test Issue. 

### ISSUE THREAD

**Issue by vladimirdubal** [kg2k1b/DAT_SF_16#3]
Hi Rick, satellite communications sounds interesting. And so does racketball. I tried to learn tennis a long time ago, but can't say i was ever particularly good at it. I'll see you you in class tonight. 

Vladimir

**Comment by kg2k1b** [comment]
Satcom is interesting, but not as much as Data Science...:)
See you in class.

P.S: this is Karan, not Rick.

**Comment by kg2k1b** [comment]
Closing this issue!!
